services:
  - type: web
    name: product-review-api
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/product-review-backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: product-review-db
          property: connectionString
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: product-review-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: product-review-db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: product-review-db
          property: password

databases:
  - name: product-review-db
    plan: free
